// Tradução para o inglês das mensagens da API. A chave é a mensagem original em português.
export const MENSAGENS_EN = {
    'A assinatura desta conta não está ativa': 'This account\'s subscription is not active',
    'A assinatura está inativa. Assine um plano para continuar usando o sistema.': 'The subscription is inactive. Subscribe to a plan to keep using the system.',
    'A assinatura foi cancelada. Assine novamente para voltar a usar o sistema.': 'The subscription was canceled. Subscribe again to keep using the system.',
    'Abrindo o pagamento': 'Opening checkout',
    'Acesso bloqueado': 'Access blocked',
    'Acesso desbloqueado': 'Access unblocked',
    'Acesso liberado': 'Access granted',
    'Acesso negado': 'Access denied',
    'Alertas salvos': 'Alerts saved',
    'A senha deve ter ao menos 6 caracteres': 'The password must have at least 6 characters',
    'Assinatura atualizada': 'Subscription updated',
    'Cliente não encontrado': 'Customer not found',
    'Conecte o Telegram antes de testar': 'Connect Telegram before testing',
    'Conta criada com sucesso': 'Account created successfully',
    'Conta não encontrada': 'Account not found',
    'Dados atualizados com sucesso': 'Details updated successfully',
    'Dados do domínio atualizados': 'Domain details updated',
    'Domínio inválido. Exemplo: meusite.com.br': 'Invalid domain. Example: mysite.com',
    'E-mail inválido: {email}': 'Invalid e-mail: {email}',
    'E-mail ou senha incorretos': 'Incorrect e-mail or password',
    'Endereço (URL) inválido': 'Invalid address (URL)',
    'Erro interno do servidor': 'Internal server error',
    'Esta conta não possui assinatura. Entre em contato com o suporte.': 'This account has no subscription. Please contact support.',
    'Este cliente paga no cartão (renova sozinho). Cancele a assinatura no cartão antes de liberar manualmente.': 'This customer pays by card (auto-renews). Cancel the card subscription before granting access manually.',
    'Este domínio já está cadastrado': 'This domain is already registered',
    'Este pagamento não pertence à sua conta': 'This payment does not belong to your account',
    'Este plano ainda não está disponível no cartão.': 'This plan is not available for card payment yet.',
    'Este plano está em uso por algum cliente. Desative-o em vez de excluir.': 'This plan is in use by a customer. Deactivate it instead of deleting.',
    'Este plano não tem preço em reais para pagamento por Pix.': 'This plan has no price in BRL for Pix payment.',
    'Informe de 1 a 365 dias': 'Enter 1 to 365 days',
    'Informe o domínio': 'Enter the domain',
    'Informe o nome': 'Enter the name',
    'Informe o nome do servidor': 'Enter the server name',
    'Informe o nome e o tipo do plano': 'Enter the plan name and type',
    'Informe seu nome e o nome da empresa': 'Enter your name and your company name',
    'Informe uma data no futuro': 'Enter a future date',
    'Informe um CPF ou CNPJ válido de quem vai pagar o Pix': 'Enter a valid CPF or CNPJ of the Pix payer',
    'Informe um e-mail válido': 'Enter a valid e-mail',
    'Já existe um usuário com este e-mail': 'A user with this e-mail already exists',
    'Login realizado com sucesso': 'Signed in successfully',
    'Mensagem de teste enviada': 'Test message sent',
    'Não conseguimos cobrar a assinatura. Atualize o cartão para voltar a usar o sistema.': 'We could not charge your subscription. Update your card to keep using the system.',
    'Não foi possível falar com o Stripe: {detalhe}': 'Could not reach Stripe: {detalhe}',
    'Não foi possível falar com o Telegram. Tente de novo em instantes.': 'Could not reach Telegram. Please try again shortly.',
    'Não foi possível gerar o Pix no Mercado Pago: {detalhe}': 'Could not create the Pix payment at Mercado Pago: {detalhe}',
    'Novo comando gerado. O comando antigo deixou de funcionar.': 'New command created. The old command no longer works.',
    'O acesso desta conta foi bloqueado pelo suporte. Entre em contato para regularizar.': 'This account was blocked by support. Please contact us.',
    'O dono da conta não pode ser removido': 'The account owner cannot be removed',
    'O Mercado Pago não devolveu o QR Code do Pix. Verifique se a conta tem uma chave Pix cadastrada.': 'Mercado Pago did not return the Pix QR code. Check that the account has a Pix key.',
    'O período de teste terminou. Assine um plano para continuar usando o sistema.': 'Your free trial has ended. Subscribe to a plan to keep using the system.',
    'O período pago terminou. Renove o pagamento para continuar usando o sistema.': 'Your paid period has ended. Renew the payment to keep using the system.',
    'O preço deste plano não foi encontrado no Stripe. Confira o "ID do preço" do plano.': 'This plan\'s price was not found in Stripe. Check the plan\'s "Price ID".',
    'O Telegram ainda não está configurado no sistema. Fale com o suporte.': 'Telegram is not set up in the system yet. Please contact support.',
    'O Telegram não aceitou a mensagem. Confira se o bot não foi bloqueado ou removido do grupo.': 'Telegram rejected the message. Check that the bot was not blocked or removed from the group.',
    'Pagamento com cartão ainda não está configurado. Fale com o suporte.': 'Card payment is not set up yet. Please contact support.',
    'Pagamento por Pix ainda não está configurado. Fale com o suporte.': 'Pix payment is not set up yet. Please contact support.',
    'Para trocar de plano, aguarde o fim do período já pago. Por enquanto você pode renovar o plano atual.': 'To change plans, wait until the paid period ends. For now you can renew the current plan.',
    'Pedido enviado. O agente atualiza os dados em até 1 minuto.': 'Request sent. The agent will update the data within 1 minute.',
    'Pix gerado com sucesso': 'Pix created successfully',
    'Plano atualizado com sucesso': 'Plan updated successfully',
    'Plano criado com sucesso': 'Plan created successfully',
    'Plano gratuito não configurado': 'Free plan is not configured',
    'Plano não encontrado': 'Plan not found',
    'Plano não encontrado ou indisponível para assinatura': 'Plan not found or not available',
    'Plano removido com sucesso': 'Plan deleted successfully',
    'Registro não encontrado': 'Record not found',
    'Requisição inválida': 'Invalid request',
    'Senha alterada com sucesso': 'Password changed successfully',
    'Senha atual incorreta': 'Current password is incorrect',
    'Senha redefinida com sucesso': 'Password reset successfully',
    'Servidor adicionado. Agora instale o agente.': 'Server added. Now install the agent.',
    'Servidor atualizado com sucesso': 'Server updated successfully',
    'Servidor não encontrado': 'Server not found',
    'Servidor removido com sucesso': 'Server deleted successfully',
    'Sessão expirada. Entre novamente.': 'Session expired. Please sign in again.',
    'Seu período pago por Pix ainda está valendo (até {data}). Assine no cartão depois dessa data.': 'Your Pix paid period is still valid (until {data}). Subscribe by card after that date.',
    'Seu plano permite até {limite} servidores. Troque de plano para adicionar mais.': 'Your plan allows up to {limite} servers. Upgrade to add more.',
    'Seu plano permite até {limite} sites. Troque de plano para adicionar mais.': 'Your plan allows up to {limite} sites. Upgrade to add more.',
    'Site adicionado com sucesso': 'Site added successfully',
    'Site atualizado com sucesso': 'Site updated successfully',
    'Site não encontrado': 'Site not found',
    'Site removido com sucesso': 'Site deleted successfully',
    'Só dá para estender o teste de quem ainda não assinou': 'You can only extend the trial of customers who have not subscribed',
    'Sua assinatura no cartão está ativa e renova sozinha. Para pagar por Pix, cancele a assinatura no cartão antes.': 'Your card subscription is active and renews automatically. To pay by Pix, cancel the card subscription first.',
    'Telegram desconectado': 'Telegram disconnected',
    'Teste estendido': 'Trial extended',
    'Token do agente inválido': 'Invalid agent token',
    'Token inválido': 'Invalid token',
    'Token não fornecido': 'Token not provided',
    'Token renovado': 'Token refreshed',
    'Usuário atualizado com sucesso': 'User updated successfully',
    'Usuário criado com sucesso': 'User created successfully',
    'Usuário não encontrado': 'User not found',
    'Usuário removido com sucesso': 'User deleted successfully',
    'Você ainda não tem assinatura no cartão.': 'You don\'t have a card subscription yet.',
    'Você já tem uma assinatura ativa no cartão. Para trocar de plano ou de cartão, use "Gerenciar no Stripe".': 'You already have an active card subscription. To change plan or card, use "Manage in Stripe".',
    'Você não pode remover a si mesmo': 'You cannot remove yourself',
    'Você saiu da conta': 'You signed out',
    'Webhook inválido': 'Invalid webhook',
    'Ação inválida': 'Invalid action',
    'As faturas deste mês e do próximo já foram geradas': 'This month\'s and next month\'s invoices have already been created',
    'Cadastre a mensalidade (itens e valores) antes de gerar a fatura': 'Set up the monthly fee (items and amounts) before creating the invoice',
    'Cliente atualizado': 'Client updated',
    'Cliente cadastrado': 'Client added',
    'Cliente removido': 'Client removed',
    'Cole a chave secreta do Stripe (começa com sk_live_ ou rk_live_).': 'Paste the Stripe secret key (starts with sk_live_ or rk_live_).',
    'Cole o "Access Token" do Mercado Pago (começa com APP_USR-).': 'Paste the Mercado Pago "Access Token" (starts with APP_USR-).',
    'Conta desconectada': 'Account disconnected',
    'Esta fatura não está em aberto': 'This invoice is not open',
    'Este link de acesso não vale mais. Peça um novo ao responsável pelo seu sistema.': 'This access link is no longer valid. Ask the person who manages your system for a new one.',
    'Este plano ainda não tem preço definido.': 'This plan has no price yet.',
    'Fatura atualizada': 'Invoice updated',
    'Fatura gerada': 'Invoice created',
    'Fatura não encontrada': 'Invoice not found',
    'Informe o nome e o e-mail do cliente': 'Enter the client\'s name and e-mail',
    'Link de renovação inválido': 'Invalid renewal link',
    'Mercado Pago conectado': 'Mercado Pago connected',
    'Não foi possível abrir o pagamento no Mercado Pago: {detalhe}': 'Could not open the Mercado Pago payment: {detalhe}',
    'Não foi possível abrir o pagamento no Stripe: {detalhe}': 'Could not open the Stripe payment: {detalhe}',
    'Não foi possível consultar a cotação do dólar agora. Tente de novo em instantes.': 'Could not get the dollar exchange rate right now. Try again shortly.',
    'No Brasil o pagamento é pelo Mercado Pago (Pix).': 'In Brazil, payment is made through Mercado Pago (Pix).',
    'O Mercado Pago não aceitou este Access Token. Confira se copiou inteiro.': 'Mercado Pago did not accept this Access Token. Check that you copied all of it.',
    'O Mercado Pago só cobra em reais. Peça ao responsável para ajustar a moeda da cobrança.': 'Mercado Pago only charges in Brazilian reais. Ask the person who manages your system to change the currency.',
    'O pagamento online ainda não foi configurado pelo responsável. Fale com ele.': 'Online payment has not been set up yet. Please contact the person who manages your system.',
    'O painel está indisponível no momento. Fale com o responsável pelo seu sistema.': 'The dashboard is unavailable right now. Please contact the person who manages your system.',
    'O Pix é só para contas do Brasil. Pague com cartão.': 'Pix is only for accounts in Brazil. Pay by card.',
    'O recebimento de pagamentos ainda não está configurado no sistema. Fale com o suporte.': 'Receiving payments is not set up in the system yet. Please contact support.',
    'O Stripe não aceitou esta chave. Confira se copiou inteira e se ela pode criar pagamentos (Checkout).': 'Stripe did not accept this key. Check that you copied all of it and that it can create payments (Checkout).',
    'Pagamento recebido pelo gateway não pode ser reaberto': 'A payment received through the gateway cannot be reopened',
    'Para cobrar, informe ao menos um item com valor': 'To charge, enter at least one item with an amount',
    'Senha criada com sucesso': 'Password created successfully',
    'Stripe conectado': 'Stripe connected',
    'Use uma conta do Mercado Pago do Brasil.': 'Use a Mercado Pago account from Brazil.',
    'Você já tem um cliente com este e-mail': 'You already have a client with this e-mail',
    'O cartão pelo Mercado Pago é só para contas do Brasil.': 'Card payment via Mercado Pago is only for accounts in Brazil.',
    'Para trocar de plano, aguarde o fim do período pago por Pix ({data}). Agora dá para passar o plano atual para o cartão.': 'To change plans, wait until the Pix period ends ({data}). For now you can move the current plan to card.',
    'Você já tem uma assinatura ativa no cartão. Para trocar de plano, cancele a atual antes.': 'You already have an active card subscription. To change plans, cancel the current one first.',
    'Não há uma assinatura no cartão para cancelar': 'There is no card subscription to cancel',
    'Assinatura cancelada': 'Subscription canceled',
    'Não foi possível falar com o Mercado Pago: {detalhe}': 'Could not reach Mercado Pago: {detalhe}',
    'O e-mail do pagador não corresponde a uma conta do Mercado Pago.': 'The payer e-mail does not match a Mercado Pago account.',
    'URL de retorno do Mercado Pago inválida. Confira a variável APP_URL no .env.': 'Invalid Mercado Pago return URL. Check APP_URL in .env.',
    'Assinatura não encontrada': 'Subscription not found',
    'Assinante cadastrado': 'Subscriber added',
    'Assinante atualizado': 'Subscriber updated',
    'Assinante excluído': 'Subscriber deleted',
    'Senha redefinida': 'Password reset',
}
